import{a as p,i as d,S as y}from"./assets/vendor-b725de7c.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerpolicy&&(n.referrerPolicy=o.referrerpolicy),o.crossorigin==="use-credentials"?n.credentials="include":o.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(o){if(o.ep)return;o.ep=!0;const n=r(o);fetch(o.href,n)}})();const g="41921784-0571e350d6104826bc1422cb3",L=document.getElementById("search-form"),u=document.getElementById("search-input"),m=document.getElementById("loader"),w=document.getElementById("gallery"),s=document.querySelector('[data-action="load-more"]');let c=1;L.addEventListener("submit",async function(e){e.preventDefault(),c=1;const t=u.value.trim();t!==""&&await f(t)});s.addEventListener("click",b);function b(){c+=1;const e=u.value.trim();e!==""&&f(e,c)}async function f(e,t=1){try{const r=await E(e,t);r.data.hits.length>0?(v(r.data.hits),h()):C(),r.data.totalHits<=t*40&&k()}catch(r){console.error("Error fetching images:",r),l(),M("An error occurred while fetching images. Please try again.")}}async function E(e,t){const r=`https://pixabay.com/api/?key=${g}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=40`;I();try{const a=await p.get(r);return l(),a}catch(a){throw l(),a}}function v(e){const t=document.createDocumentFragment();e.forEach(r=>{const a=$(r);t.appendChild(a)}),w.appendChild(t),e.length>0?s.style.display="block":s.style.display="none"}function I(){m.style.display="block"}function l(){m.style.display="none"}function $(e){const t=document.createElement("div");return t.className="image-card",t.innerHTML=`
    <a href="${e.largeImageURL}" data-lightbox="gallery">
      <img src="${e.webformatURL}" alt="${e.tags}">
    </a>
    <div class="image-details">
      <p>Likes: ${e.likes}</p>
      <p>Views: ${e.views}</p>
      <p>Comments: ${e.comments}</p>
      <p>Downloads: ${e.downloads}</p>
    </div>
  `,t}function C(){d.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"})}function M(e){d.error({title:"Error",message:e})}function k(){d.info({title:"End of Collection",message:"We're sorry, but you've reached the end of search results."}),s.style.display="none"}function h(){new y(".image-card a")}document.addEventListener("DOMContentLoaded",h);
//# sourceMappingURL=commonHelpers.js.map
